- name: Install backup_runner
  hosts: homelab

  tasks:
      - name: Copy source files
        ansible.builtin.copy:
            src: "backup_runner/{{ item }}"
            dest: ~/backup_runner/
            mode: u=rwx
        loop:
            - "Cargo.toml"
            - "src"
            - "templates"

      - name: Build and install to ~/.cargo/bin/backup_runner
        register: cargo_install
        changed_when: cargo_install.rc == 0
        ansible.builtin.command: cargo install --path=./backup_runner
