- Media:
      - Jellyfin:
            href: "https://media.{{ base_domain }}"
            icon: jellyfin.png
            widget:
                enableBlocks: true # optional, defaults to false
                enableNowPlaying: false # optional, defaults to true
                key: "{{ api_keys.jellyfin }}"
                type: jellyfin
                url: "http://{{ ansible_wg0.ipv4.address }}:{{ network.service_ports.jellyfin }}"
      - Deemix:
            href: "https://deemix.{{ base_domain }}"
            icon: mdi-folder-music
      - QBittorrent:
            href: "https://qbit.{{ base_domain }}"
            icon: qbittorrent.png
            widget:
                password: "{{ api_keys.qbittorrent }}"
                type: qbittorrent
                url: "http://{{ ansible_wg0.ipv4.address }}:{{ network.service_ports.qbittorrent_web_ui }}"
                username: admin
      - Radarr:
            href: "https://radarr.{{ base_domain }}"
            icon: radarr.png
            widget:
                enableQueue: true
                key: "{{api_keys.radarr }}"
                type: radarr
                url: "http://{{ ansible_wg0.ipv4.address }}:{{ network.service_ports.radarr }}"
      - Sonarr:
            href: "https://sonarr.{{ base_domain }}"
            icon: sonarr.png
            widget:
                enableQueue: true
                key: "{{ api_keys.sonarr }}"
                type: sonarr
                url: "http://{{ ansible_wg0.ipv4.address }}:{{ network.service_ports.sonarr }}"
      - Jackett:
            href: "https://jackett.{{ base_domain }}"
            icon: jackett.png

- Services:
      - Photoprism:
            href: "https://gallery.{{ base_domain }}/"
            icon: photoprism.png
      - Trilium:
            href: "https://notes.{{ base_domain }}/"
            icon: trilium.png
      - Documents:
            href: "https://documents.{{ base_domain }}/"
            icon: file-browser.svg
      - Storage:
            href: "https://storage.{{ base_domain }}/"
            icon: hoodik.svg
      - Jupyter Notebooks:
            href: "https://jupyter.{{ base_domain }}/"
            icon: jupyter.png

- Management:
      - Unifi:
            href: https://10.1.1.1/
            icon: unifi.png
            widget:
                password: "{{ api_keys.unifi.password }}"
                type: unifi
                url: https://10.1.1.1
                username: "{{ api_keys.unifi.username }}"

      - PiHole:
            href: "https://pihole.{{ base_domain }}/admin/"
            icon: pi-hole.png
      - LLDAP:
            href: "https://ldap.{{ base_domain }}"
            icon: mdi-account-box-multiple
      - Grafana:
            href: "https://grafana.{{ base_domain }}"
            icon: grafana.png
