- datetime:
      format:
          timeStyle: short
      locale: fi
      text_size: xl
- openmeteo:
      cache: 5
      label: Turku
      latitude: 60.4517531
      longitude: 22.2670522
      timezone: Europe/Helsinki
      units: metric

- search:
      provider: google
      target: _self
