- datetime:
      text_size: xl
      locale: fi
      format:
          timeStyle: short

- openmeteo:
      label: Turku
      latitude: 60.4517531
      longitude: 22.2670522
      timezone: Europe/Helsinki
      units: metric
      cache: 5

- search:
      provider: duckduckgo
      target: _self
