global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["127.0.0.1:9090"]
# Podman exporter scrape configs are generated automatically
scrape_config_files:
    - /prometheus/scrape_podman_exporter.yml
