global:
    evaluation_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 10s
scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["127.0.0.1:9090"]
    - job_name: "authelia"
      scrape_interval: "30s"
      scheme: "http"
      static_configs:
          - targets:
                [
                    "{{ network.internal_ip }}:{{ network.service_ports.authelia_metrics }}",
                ]
    - job_name: "qbittorrent"
      scrape_interval: "30s"
      scheme: "http"
      static_configs:
          - targets:
                [
                    "{{ network.internal_ip }}:{{ network.service_ports.qbittorrent_exporter }}",
                ]
    - job_name: "node_exporter"
      scrape_interval: "30s"
      scheme: "http"
      static_configs:
          - targets:
                [
                    "{{ network.internal_ip }}:{{ network.service_ports.node_exporter }}",
                ]
# Podman exporter scrape configs are generated automatically
#scrape_config_files:
#    - /prometheus/scrape_configs/authelia.yml
