- name: Run all services
  hosts: homelab

- name: Run pihole
  ansible.builtin.import_playbook: pihole.yml

- name: Run nginx
  ansible.builtin.import_playbook: nginx.yml

- name: Run lldap
  ansible.builtin.import_playbook: lldap.yml

- name: Run authelia
  ansible.builtin.import_playbook: authelia.yml
