- name: SFTPGo file archive
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: archive
          user: archive

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - data
                    - home

      - name: SFTPGo container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/drakkan/sftpgo:{{ versions.sftpgo }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.sftpgo }}:2022"
                - "{{ network.internal_ip }}:{{ network.service_ports.sftpgo_web }}:80801"
            user: "{{ ansible_user_id }}:{{ ansible_user_id }}"
            volume:
                # Persistent data, user home directories
                - "{{ dirs_container_volume_subdirectories.results[0].path }}:/srv/sftpgo"
                # Home directory for the sftpgo system user
                - "{{ dirs_container_volume_subdirectories.results[1].path }}:/var/lib/sftpgo"
