- name: SFTPGo file archive
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: archive
          user: archive

  roles:
      - service_user

      - role: directories
        directories_options:
            volume:
                subdirectories:
                    - data
                    - home

  tasks:
      - name: SFTPGo container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/drakkan/sftpgo:{{ versions.sftpgo }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.sftpgo }}:2022"
                - "{{ network.internal_ip }}:{{ network.service_ports.sftpgo_web }}:8080"
            user: "{{ ansible_user_id }}:{{ ansible_user_id }}"
            volume:
                # Persistent data, user home directories
                - "{{ directories_volume_subdirectories_output.results[0].path }}:/srv/sftpgo"
                # Home directory for the sftpgo system user
                - "{{ directories_volume_subdirectories_output.results[1].path }}:/var/lib/sftpgo"
