- name: Deemix Deezer downloader
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: deemix
          user: deemix

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - config

      - name: Deemix container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: registry.gitlab.com/bockiii/deemix-docker
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.deemix }}:6595"
            volumes:
                - "{{ dirs_container_volume_subdirectories.results[0].path }}:/config"
                - "{{ filesystem.media.music }}:/downloads"
