- name: Deemix Deezer downloader
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: deemix
          user: deemix
      volumes:
          subdirectories:
              - config

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Deemix container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: registry.gitlab.com/bockiii/deemix-docker
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ container_log_directory_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.deemix }}:6595"
            volumes:
                - "{{ volume_subdirectory_output.results[0].path }}:/config"
                - "{{ filesystem.media.music }}:/downloads"
