- name: Deemix Deezer downloader
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: deemix
          user: deemix

  roles:
      - role: service_user

      - role: directories
        directories_options:
            volume:
                subdirectories:
                    - config

  tasks:
      - name: Deemix container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: registry.gitlab.com/bockiii/deemix-docker
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.deemix }}:6595"
            volumes:
                - "{{ directories_volume_subdirectories_output.results[0].path }}:/config"
                - "{{ filesystem.media.music }}:/downloads"
