- name: Web file browser UI for document storage
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: filebrowser_documents
          user: filebrowser_documents

  roles:
      - service_user

      - role: directories
        directories_options:
            volume:
                subdirectories:
                    - config
                    - database
                    - data

  tasks:
      - name: Copy config file
        ansible.builtin.copy:
            src: ./configs/filebrowser_documents.json
            dest: "{{ directories_volume_subdirectories_output.results[0].path }}/settings.json"
            owner: "{{ service.user }}"
            group: "{{ service.user }}"
            mode: u=rwx

      - name: Filebrowser container (documents)
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/filebrowser/filebrowser:{{ versions.filebrowser }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.filebrowser_documents }}:80"
            user: "{{ ansible_user_id }}"
            volumes:
                - "{{ directories_volume_subdirectories_output.results[0].path }}:/config"
                - "{{ directories_volume_subdirectories_output.results[1].path }}:/database"
                - "{{ directories_volume_subdirectories_output.results[2].path }}:/data"
