- name: Frigate NVR
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: frigate
          user: frigate

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - config
                    - storage
            directories_container_cache:
                create: true

      - name: Frigate container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "ghcr.io/blakeblackshear/frigate:{{ versions.frigate }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.frigate_web }}:8971"
            volumes:
                - "{{ dirs_container_volume_subdirectories.results[0].path }}:/config"
                - "{{ dirs_container_volume_subdirectories.results[1].path }}:/media/frigate"
                - "{{ dirs_container_cache.path }}:/tmp/cache"
            device:
                - nvidia.com/gpu=all
            env:
                NVIDIA_DRIVER_CAPABILITIES: all
                NVIDIA_VISIBLE_DEVICES: all
            group_add:
                - keep-groups
            shm_size: 256mb
