- name: Frigate NVR
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: frigate
          user: frigate
      rstp_user:
          username: nvr_rtsp
          password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              33663338353164613962326262323434643539663733313931626138323030613061636532386236
              6334663966653735613163626633373666383238363765610a643031306662363931616165613761
              61643337616537376638623536386131343837366331303633643161613666313736636461303631
              3139663062373231330a323362643432316634316239356432353034316666323361393238376234
              32373433396461363264643730313137613038363362393138656266636332623438

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - config

      # - name: Copy config template
      #   ansible.builtin.template:
      #       src: configs/frigate.yml
      #       dest: "{{ dirs_container_volume_subdirectories.results[0].path }}/config.yaml"
      #       mode: u=rw

      - name: Frigate container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "ghcr.io/blakeblackshear/frigate:stable-tensorrt"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.frigate_web }}:8971"
            volumes:
                - "{{ dirs_container_volume_subdirectories.results[0].path }}:/config"
                # Storage on custom path
                - "{{ filesystem.media.nvr }}:/media/frigate"
            mounts:
                # Cache in RAM
                - type=tmpfs,tmpfs-size=1024M,destination=/tmp/cache
            device:
                - nvidia.com/gpu=all
            env:
                NVIDIA_DRIVER_CAPABILITIES: all
                NVIDIA_VISIBLE_DEVICES: all
                YOLO_MODELS: yolov7-320,yolov7x-640
            group_add:
                - keep-groups
            shm_size: 256mb
