- name: Grafana monitoring dashboard
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: grafana
          user: grafana

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Grafana container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/grafana-oss
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ container_log_directory_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            user: "{{ ansible_user_id }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.grafana }}:3000"
            volumes:
                - "{{ volume_directory_output.path }}:/var/lib/grafana"
