- name: Grafana monitoring dashboard
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: grafana
          user: grafana

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true

      - name: Grafana container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/grafana-oss
            network: "{{ podman.network }}"
            user: "{{ ansible_user_id }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.grafana }}:3000"
            volumes:
                - "{{ dirs_container_volume.path }}:/var/lib/grafana"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
