- name: Storage service
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: hoodik
          user: hoodik

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - data
                    - postgresql_data

      - name: Service test pod
        ansible.builtin.import_role:
            name: pod

      - name: DB
        ansible.builtin.import_role:
            name: postgresql
        vars:
            postgresql_user:
                username: "{{ service.name }}"
                password: password
                database: "{{ service.name }}"
            postgresql_volume_path: "{{ dirs_container_volume_subdirectories.results[1].path }}"
            postgresql_log_path: "{{ dirs_container_logs }}"
