- name: Storage service
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: hoodik
          user: hoodik

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user
        vars:
            service_user_name: "{{ service.user }}"

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_permissions:
                user: "{{ service.user }}"
            directories_volume:
                create: true
