- name: Jellyfin media player
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: jellyfin
          user: jellyfin
      volumes:
          cache_directories:
              - transcodes

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Jellyfin container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/jellyfin/jellyfin:{{ versions.jellyfin }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ container_log_directory_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.jellyfin }}:8096"
            env:
                PUID: 0
                PGID: 0
                # Not sure if these even do anything
                NVIDIA_DRIVER_CAPABILITIES: all
                NVIDIA_VISIBLE_DEVICES: all
            device:
                - nvidia.com/gpu=all
            volumes:
                - "{{ volume_directory_output.path }}:/config"
                - "{{ cache_directories_output.results[0].path }}:/cache"
                - "{{ filesystem.media.movies }}:/media/movies"
                - "{{ filesystem.media.series }}:/media/series"
                - "{{ filesystem.media.music }}:/media/music"
