- name: Jellyfin media player
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: jellyfin
          user: jellyfin

  roles:
      - role: service_user
        service_user_options:
            groups:
                - media

      - role: directories
        directories_options:
            cache:
                create: true

  tasks:
      - name: Regenerate CDI spec
        register: cdi_spec_output
        changed_when: '"Generated CDI spec" in cdi_spec_output.stdout'
        ansible.builtin.command: /usr/bin/nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml

      - name: Jellyfin container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/jellyfin/jellyfin:{{ versions.jellyfin }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.jellyfin }}:8096"
            env:
                PUID: 0
                PGID: 0
                # Not sure if these even do anything
                NVIDIA_DRIVER_CAPABILITIES: all
                NVIDIA_VISIBLE_DEVICES: all
            device:
                - nvidia.com/gpu=all
            volumes:
                - "{{ directories_volume_output.path }}:/config"
                - "{{ directories_cache_output.path }}:/cache"
                - "{{ filesystem.media.movies }}:/media/movies"
                - "{{ filesystem.media.series }}:/media/series"
                - "{{ filesystem.media.music }}:/media/music"
