- name: Centralized log storage
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: loki
          user: loki

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Copy config template
        ansible.builtin.template:
            src: configs/loki.yml
            dest: "{{ volume_directory_output.path }}/config.yml"
            owner: "{{ service.user }}"
            group: "{{ service.user }}"
            mode: u=rw

      - name: Loki container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/loki
            log_driver: json-file
            log_options:
                path: "{{ container_log_directory_output.path }}/container.log"
            restart_policy: on-failure
            network:
                - pasta
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.loki }}:3100"
            volumes:
                - "{{ volume_directory_output.path }}:/loki"
            command: -config.file=/loki/config.yml
