- name: Log database
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: loki
          user: loki

  roles:
      - service_user
      - directories

  tasks:
      - name: Copy config template
        ansible.builtin.template:
            src: configs/loki.yml
            dest: "{{ directories_volume_output.path }}/config.yml"
            owner: "{{ service.user }}"
            group: "{{ service.user }}"
            mode: u=rw

      - name: Loki container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/loki
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            user: "{{ ansible_user_id }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.loki }}:3100"
            volumes:
                - "{{ directories_volume_output.path }}:/loki"
            command: -config.file=/loki/config.yml
