- name: Minecraft server
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: minecraft
          user: minecraft

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true

      - name: Server container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/itzg/minecraft-server
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.external_ip }}:{{ network.service_ports.minecraft }}:25565"
            volumes:
                - "{{ dirs_container_volume.path }}:/data"
            env:
                EULA: "TRUE"
                VERSION: "1.21.1"
                MEMORY: "8G"
            dns_servers:
                - "1.1.1.1"
                - "8.8.8.8"
