- name: Photoprism gallery
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: photoprism
          user: photoprism
      admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61343837656230616237396539333362653331303461633331383566356433353537646135616536
          3130633665653134623135616331343131303065396562370a396137636261653461313333666134
          36323133356166396537373230396165633238386231356366663964633862386539636333626666
          3634303239346539350a363436323537623532343761643238343063353265633330306666343237
          32306361653266336638343966326631633762646638346263636635306435383333

  roles:
      - service_user

      - role: directories
        directories_options:
            volume:
                subdirectories:
                    - config
                    - originals
                    - import

  tasks:
      - name: Photoprism container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/photoprism/photoprism
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            env:
                PHOTOPRISM_ADMIN_PASSWORD: "{{ admin_password }}"
                PHOTOPRISM_RESOLUTION_LIMIT: 900
                PHOTOPRISM_ORIGINALS_LIMIT: 5000 # MB
                PHOTOPRISM_IMPORT_PATH: /photoprism/import
                PHOTOPRISM_SITE_URL: "https://gallery.{{ base_domain }}/"
                PHOTOPRISM_SITE_TITLE: "gallery.{{ base_domain }}"
                PHOTOPRISM_SITE_CAPTION: "gallery.{{ base_domain }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.photoprism }}:2342"
            volumes:
                # Database and so on
                - "{{ directories_volume_subdirectories_output.results[0].path }}:/photoprism/storage"
                # Actual original images
                - "{{ directories_volume_subdirectories_output.results[1].path }}:/photoprism/originals"
                # Import folder
                - "{{ directories_volume_subdirectories_output.results[2].path }}:/photoprism/import"
