- name: Pihole service
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: pihole
          user: pihole
      volumes:
          subdirectories:
              - pihole
              - dnsmasq.d

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Pihole container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/pihole/pihole:{{ versions.pihole }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ container_log_directory_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.external_ip }}:{{ network.exposed_ports.pihole_dns }}:53/tcp"
                - "{{ network.external_ip }}:{{ network.exposed_ports.pihole_dns }}:53/udp"
                - "{{ network.internal_ip }}:{{ network.service_ports.pihole_admin }}:80"
            volume:
                - "{{ volume_directory_output.path }}/pihole:/etc/pihole"
                - "{{ volume_directory_output.path }}/dnsmasq.d:/etc/dnsmasq.d"
