- name: Pihole service
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: pihole
          user: pihole

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true
                subdirectories:
                    - config
                    - dnsmasq.d

      - name: Pihole container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/pihole/pihole:{{ versions.pihole }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            publish:
                - "{{ network.external_ip }}:{{ network.exposed_ports.pihole_dns }}:53/tcp"
                - "{{ network.external_ip }}:{{ network.exposed_ports.pihole_dns }}:53/udp"
                - "{{ network.internal_ip }}:{{ network.service_ports.pihole_admin }}:80"
            volume:
                - "{{ dirs_container_volume_subdirectories.results[0].path }}:/etc/pihole"
                - "{{ dirs_container_volume_subdirectories.results[1].path }}:/etc/dnsmasq.d"
            env:
                PIHOLE_UID: 0
                PIHOLE_GID: 0
                DNSMASQ_USER: root
                INTERFACE: enp3s0
