- name: Promtail
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: promtail
          user: promtail

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      # Required to access system journal
      - name: Add user to systemd-journal
        ansible.builtin.user:
            user: "{{ service.user }}"
            append: true
            groups:
                - systemd-journal

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Copy config template
        ansible.builtin.template:
            src: configs/promtail.yml
            dest: "{{ volume_directory_output.path }}/config.yml"
            owner: "{{ service.user }}"
            group: "{{ service.user }}"
            mode: u=rw

      - name: Promtail container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/promtail
            log_driver: k8s-file
            log_options:
                path: "{{ container_log_directory_output.path }}/container_log"
            restart_policy: on-failure
            network:
                - pasta
            user: "{{ ansible_user_id }}"
            volumes:
                - "{{ volume_directory_output.path }}:/data"
                - "{{ filesystem.container_logs }}:/container_logs:ro"
                - "/var/log/journal/:/var/log/journal/:ro"
            command: -config.file=/data/config.yml
