- name: Promtail
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: promtail
          user: promtail

  roles:
      - role: service_user
        service_user_options:
            groups:
                - systemd-journal
                - podman-logs

      - directories

  tasks:
      - name: Copy config template
        ansible.builtin.template:
            src: configs/promtail.yml
            dest: "{{ directories_volume_output.path }}/config.yml"
            owner: "{{ service.user }}"
            group: "{{ service.user }}"
            mode: u=rw

      - name: Promtail container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: docker.io/grafana/promtail
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            # Required to allow reads permitted by groups on the service user
            groups:
                - keep-groups
            volumes:
                - "{{ directories_volume_output.path }}:/data"
                - "{{ filesystem.container_logs }}:/var/log/containers:ro"
                - "/var/log/journal/:/var/log/journal/:ro"
            command: -config.file=/data/config.yml

      - name: Keep starting every 5min, as can crash with temporary missing permissions
        become: true
        become_user: "{{ service.user }}"
        ansible.builtin.cron:
            name: start_promtail_container
            minute: "*/5"
            job: podman start "{{ service.name }}"
