- name: Torrent tracker manager
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: prowlarr
          user: prowlarr

  roles:
      - service_user
      - directories

  tasks:
      - name: Prowlarr container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "lscr.io/linuxserver/prowlarr:{{ versions.prowlarr }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network:
                # Allow this container to reach the host
                - pasta:--map-gw
            volumes:
                - "{{ directories_volume_output.path }}:/config"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.prowlarr }}:9696"
            env:
                PUID: "{{ ansible_user_id }}"
                PGID: "{{ ansible_user_id }}"
                TZ: Europe/Helsinki
