- name: Movie download manager
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: radarr
          user: radarr

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Radarr container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            image: lscr.io/linuxserver/radarr
            state: "{{ container_state | default('started') }}"
            log_driver: k8s-file
            log_options:
                path: "{{ container_log_directory_output.path }}/container_log"
            restart_policy: ”{{ podman.restart_policy }}"
            network: "{{ podman.network }}"
            volumes:
                - "{{ volume_directory_output.path }}:/config"
                # - "{{ filesystem.media.movies }}:/media/movies"
                # - "{{ filesystem.media.downloads }}:/media/downloads"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.radarr }}:7878"
            env:
                PUID: "{{ ansible_user_id }}"
                PGID: "{{ ansible_user_id }}"
                TZ: Europe/Helsinki
