- name: Series download manager
  hosts: marion
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: sonarr
          user: sonarr

  roles:
      - service_user
      - directories

  tasks:
      - name: Sonarr container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "lscr.io/linuxserver/sonarr:{{ versions.sonarr }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ directories_logs_output.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            network: "{{ podman.network }}"
            volumes:
                - "{{ directories_volume_output.path }}:/config"
                - "{{ filesystem.media.series }}:/media/series"
                - "{{ filesystem.media.downloads }}:/media/downloads"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.sonarr }}:8989"
            env:
                PUID: "{{ ansible_user_id }}"
                PGID: "{{ ansible_user_id }}"
                TZ: Europe/Helsinki
