- name: Series download manager
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: sonarr
          user: sonarr

  tasks:
      - name: Service user
        ansible.builtin.include_tasks: tasks/service_user.yml

      - name: Volume directories
        ansible.builtin.include_tasks: tasks/volume_directory.yml

      - name: Sonarr container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: lscr.io/linuxserver/sonarr
            volumes:
                - "{{ volume_directory_output.path }}:/config"
                # - "{{ filesystem.media.series }}:/media/series"
                # - "{{ filesystem.media.downloads }}:/media/downloads"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.sonarr }}:8989"
            env:
                PUID: "{{ ansible_user_id }}"
                PGID: "{{ ansible_user_id }}"
                TZ: Europe/Helsinki
