# Run this as root.
#
# Returns the path to the volume directory of the service as volume_directory_output.path.
#
# A list of subdirectories is returned (if requested) as volume_subdirectory_output.results,
# which includes the paths volume_subdirectory_output.results[0].path.
#
# Log directory is accessible with log_directory_output.path.
#
# If requested, cache directories are returned as cache_directory_output.results.

- name: Directory and permissions
  register: volume_directory_output
  ansible.builtin.file:
      path: "{{ filesystem.container_volumes }}/{{ service.name }}"
      state: directory
      owner: "{{ service.user }}"
      group: "{{ service.user }}"
      mode: u=rwx

- name: Create log directory if requested
  when: volumes.logs is defined
  register: log_directory_output
  ansible.builtin.file:
      path: "{{ filesystem.container_logs }}/{{ volumes.logs }}"
      state: directory
      owner: "{{ service.user }}"
      group: "{{ service.user }}"
      mode: u=rwx

- name: Create cache directory if requested
  when: volume.cache_directories is defined
  register: cache_directory_output
  ansible.builtin.file:
      path: "{{ filesystem.cache }}/{{ service.name }}/{{ item }}"
      state: directory
      owner: "{{ service.user }}"
      group: "{{ service.user }}"
      mode: u=rwx
  loop: "{{ volumes.cache_directories }}"

- name: Create subdirectories if requested
  when: volumes.subdirectories is defined
  register: volume_subdirectory_output
  ansible.builtin.file:
      path: "{{ filesystem.container_volumes }}/{{ service.name }}/{{ item }}"
      state: directory
      owner: "{{ service.user }}"
      group: "{{ service.user }}"
      mode: u=rwx
  loop: "{{ volumes.subdirectories }}"
