auth_enabled: false

server:
    http_listen_port: 3100
    log_level: warn

common:
    path_prefix: /loki
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory
    replication_factor: 1
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules

query_range:
    results_cache:
        cache:
            embedded_cache:
                enabled: true
                max_size_mb: 500
    split_queries_by_interval: 0
    parallelise_shardable_queries: false

querier:
    max_concurrent: 2048

frontend:
    max_outstanding_per_tenant: 4096
    compress_responses: true

schema_config:
    configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h
