positions:
    filename: /data/positions.yaml

server:
    log_level: info

clients:
    - url: "http://{{ network.internal_ip }}:{{ network.service_ports.loki }}/loki/api/v1/push"

scrape_configs:
    - job_name: journal
      journal:
          json: false
          max_age: 24h
          path: /var/log/journal
          labels:
              job: systemd-journal
      relabel_configs:
          - source_labels: ["__journal__systemd_unit"]
            target_label: "systemd_unit"
          - source_labels: ["__journal__hostname"]
            target_label: "hostname"
          - source_labels: ["__journal_syslog_identifier"]
            target_label: "syslog_identifier"
    - job_name: nginx_access_log
      static_configs:
          - targets:
                - localhost
            labels:
                job: nginx_access_log
                __path__: "/container_logs/nginx/access_log"
