- name: Service status monitor
  hosts: homelab
  remote_user: root

  vars_files:
      - ../global.yml

  vars:
      service:
          name: uptime_kuma
          user: uptime_kuma

  tasks:
      - name: User
        ansible.builtin.import_role:
            name: service_user

      - name: Directories
        ansible.builtin.import_role:
            name: directories
        vars:
            directories_container_volume:
                create: true

      - name: Uptime Kuma container
        become: true
        become_user: "{{ service.user }}"
        containers.podman.podman_container:
            name: "{{ service.name }}"
            state: "{{ container_state | default('started') }}"
            image: "docker.io/louislam/uptime-kuma:{{ versions.uptime_kuma }}"
            log_driver: "{{ podman.log_driver }}"
            log_options:
                path: "{{ dirs_container_logs.path }}/{{ podman.container_log_file }}"
            restart_policy: "{{ podman.restart_policy | regex_replace('[^A-Za-z0-9-:]', '') }}"
            publish:
                - "{{ network.internal_ip }}:{{ network.service_ports.uptime_kuma }}:3001"
            volume:
                - "{{ dirs_container_volume.path }}:/app/data"
            network:
                # Allow this container to reach the host
                - pasta:--map-gw
