# Notes:
# - Initially the file can be set by hand, but updating it this way keeps it the correct version here

- name: Configure SSH server
  hosts: homelab

  tasks:
      - name: Copy authorized keys
        ansible.builtin.copy:
            src: ../secrets/ssh/authorized_keys
            dest: /root/.ssh/authorized_keys
            mode: a=,u=rw

      - name: Copy private key
        ansible.builtin.copy:
            src: ../secrets/ssh/id_ed25519
            dest: /root/.ssh/id_ed25519
            mode: a=,u=rw

      - name: Copy public key
        ansible.builtin.copy:
            src: ../secrets/ssh/id_ed25519.pub
            dest: /root/.ssh/id_ed25519.pub
            mode: a=r,u+w

      - name: Copy config snippets
        ansible.builtin.copy:
            src: configs/ssh/
            dest: /etc/ssh/sshd_config.d/
            mode: a=,u=rw

      - name: Restart sshd
        ansible.builtin.systemd:
            name: sshd
            state: restarted
