# Notes:
# - Forwarding to LAN is done with a command in wg0.conf
# - The forwarding rules assume that the LAN interface is enp3s0!

- name: Configure wireguard for remote access
  hosts: homelab

  tasks:
      - name: Copy config
        ansible.builtin.copy:
            src: ../secrets/wg/marion/wg0.conf
            dest: /etc/wireguard/wg0.conf
            mode: a=,u=rw

      - name: Automatic start
        ansible.builtin.systemd_service:
            name: wg-quick@wg0
            state: started
            enabled: true
