- name: Configure everything podman related
  hosts: homelab

  tasks:
      - name: Allow rootless bind to ports lower than 1024
        ansible.posix.sysctl:
            name: net.ipv4.ip_unprivileged_port_start
            # DNS in the lowest port running rootless
            value: 53
            reload: true

      # https://bbs.archlinux.org/viewtopic.php?id=266915
      # - name: Fix nvidia-container-runtime config
      #   ansible.builtin.lineinfile:
      #       path: /etc/nvidia-container-runtime/config.toml
      #       regexp: .*no-cgroups = false
      #       line: no-cgroups = false

      # Fails if no nvidia GPU installed
      - name: Generate Nvidia container toolkit CDI spec for GPU # noqa no-changed-when
        ansible.builtin.command: nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
