- name: Set up Let's Encrypt certs with automatic renewals
  hosts: homelab

  vars_files:
      - ../global.yml

  vars:
      cf_token_file: /root/secrets/cloudflare_certbot_token

  tasks:
      - name: Make sure secrets directory exists
        ansible.builtin.file:
            path: /root/secrets
            state: directory
            mode: a=,u=rw

      - name: Make sure Cloudflare token exists
        ansible.builtin.lineinfile:
            path: "{{ cf_token_file }}"
            line: "dns_cloudflare_api_token = {{ external_tokens.cloudflare }}"
            create: true
            mode: a=,u=rw

      - name: Create or renew ACME cert with DNS challenge
        register: cmd
        changed_when: cmd.rc != 0
        ansible.builtin.command: >
            certbot certonly \
              --non-interactive \
              --agree-tos \
              --dns-cloudflare \
              --email {{ contact_email }} \
              --dns-cloudflare-credentials {{ cf_token_file }} \
              --dns-cloudflare-propagation-seconds 120 \
              --cert-name {{ base_domain }} \
              --preferred-chain "ISRG Root X1" \
              -d {{ base_domain }} \
              -d *.{{ base_domain }}

      - name: Automatic daily renewal (if expiring in 30 days)
        ansible.builtin.cron:
            name: "cerbot_renew_{{ base_domain }}"
            minute: 0
            hour: 18
            job: certbot renew
