- name: Set up common directories or mounts and their permissions
  hosts: homelab

  vars_files:
      - ../global.yml

  tasks:
      - name: Music library
        ansible.builtin.file:
            path: "{{ filesystem.media.music }}"
            state: directory
            recurse: true
            mode: a=rwx

      # Subdirectories are more restrictive
      - name: Container volume directory
        ansible.builtin.file:
            path: "{{ filesystem.container_volumes }}"
            state: directory
            owner: root
            group: root
            mode: a=rwx

      - name: Container log directory
        ansible.builtin.file:
            path: "{{ filesystem.container_logs }}"
            state: directory
            owner: root
            group: root
            mode: a=rwx

      # 4TB media disk
      - name: Mount hdd4tb in fstab
        ansible.posix.mount:
            state: mounted
            src: UUID=ae693b30-85d3-4f0e-b78b-7220989d30d1
            path: "{{ filesystem.mounts.hdd4tb }}"
            fstype: ext4
            opts: defaults

      - name: Virtual machine directories
        ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: root
            group: root
            mode: a=,u=rwx
        loop:
            - "{{ filesystem.vm_disks }}"
            - "{{ filesystem.vm_directories }}"

      - name: Deluge download directory
        ansible.builtin.file:
            path: "{{ filesystem.media.downloads }}"
            state: directory
            owner: root
            group: root
            mode: a=rwx
