- name: Configure SSH server
  hosts: homelab

  vars_files:
      - ../global.yml

  tasks:
      - name: Allowed ports
        community.general.ufw:
            rule: allow
            port: "{{ item }}"
        loop:
            - "22"
            - "53"
            - "80"
            - "443"
            - "444"
            - "1111"
            - "25565"

      - name: Allow Jellyfin access directly from VPN
        community.general.ufw:
            rule: allow
            port: "{{ network.service_ports.jellyfin }}"
            from: 10.1.3.0/24

      - name: Enable
        community.general.ufw:
            state: enabled
