- name: Configure SSH server
  hosts: marion

  vars_files:
      - ../global.yml

  tasks:
      - name: Allowed ports from anywhere
        community.general.ufw:
            rule: allow
            port: "{{ item }}"
        loop:
            - "22"
            - "53"
            - "80"
            - "443"
            - "444"
            - "1111"
            - "25565"

      - name: Allowed ports from VPN
        community.general.ufw:
            rule: allow
            port: "{{ item }}"
            from_ip: 10.1.3.0/24
        loop:
            - "3036"

      - name: Allow VPN passthrough traffic
        community.general.ufw:
            rule: allow
            direction: " {{ item }}"
            interface: wg0
        loop:
            - in
            - out

      - name: Allow Jellyfin access directly from VPN
        community.general.ufw:
            rule: allow
            port: "{{ network.service_ports.jellyfin }}"
            from: 10.1.3.0/24

      - name: Enable
        ansible.builtin.systemd:
            service: ufw
            state: started
            enabled: true
