- name: Install and run node_exporter + NVIDIA exporter
  hosts: homelab

  vars_files:
      - ../global.yml

  vars:
      dcgm_exporter_repo_path: /tmp/dcgm_exporter

  tasks:
      #
      # Node exporter
      #
      - name: Install
        community.general.pacman:
            package:
                - prometheus-node-exporter

      - name: Configure listen address and port
        ansible.builtin.lineinfile:
            line: 'NODE_EXPORTER_ARGS="--web.listen-address={{ network.internal_ip }}:{{ network.service_ports.node_exporter }}"'
            path: /etc/conf.d/prometheus-node-exporter
            regexp: "^NODE_EXPORTER_ARGS="

      - name: Start and enable node_exporter
        ansible.builtin.systemd:
            service: prometheus-node-exporter
            state: started
            enabled: true
            daemon_reload: true

      #
      # DCGM-Exporter
      #
      # - name: Clone DCGM-Exporter
      #   ansible.builtin.git:
      #       repo: https://github.com/NVIDIA/dcgm-exporter.git
      #       dest: "{{ ddcgm_exporter_repo_path }}"
      #       clone: true

      # - name: Build DCGM-Exporter
      #   register: dcgm_exporter_build
      #   changed_when: dcgm_exporter_build.rc == 0
      #   ansible.builtin.command:
      #       chdir: "{{ ddcgm_exporter_repo_path }}"
      #       cmd: make binary

      # - name: Build DCGM-Exporter
      #   register: dcgm_exporter_install
      #   changed_when: dcgm_exporter_install.rc == 0
      #   ansible.builtin.command:
      #       chdir: "{{ ddcgm_exporter_repo_path }}"
      #       cmd: make install

      # - name: Check that DCGM-Exporter works
      #   register: dcgm_exporter_test
      #   failed_when: dcgm_exporter_test.rc != 0
      #   ansible.builtin.command:
      #       cmd: dcgm-exporter --version