- name: Install and run node_exporter
  hosts: homelab

  vars_files:
      - ../global.yml

  tasks:
      - name: Install
        community.general.pacman:
            package:
                - prometheus-node-exporter

      - name: Configure listen address and port
        ansible.builtin.lineinfile:
            line: 'NODE_EXPORTER_ARGS="--web.listen-address={{ network.internal_ip }}:{{ network.service_ports.node_exporter }}"'
            path: /etc/conf.d/prometheus-node-exporter
            regexp: "^NODE_EXPORTER_ARGS="

      - name: Start and enable node_exporter
        ansible.builtin.systemd:
            service: prometheus-node-exporter
            state: started
            enabled: true
            daemon_reload: true
